### ISSUE TITLE
How to implement limit per identity?

### ISSUE THREAD

**Issue by kayhantolga** [ThrottlingTroll/ThrottlingTroll#19]
How to implement limit per identity? Imagine we have 100k clients and different rules (or rules set) per client. The current implementation, as I understand it, requires creating a rule per key and using IdentityId to determine which rule is applicable for the client. In this scenario, I would need to add 100k clients, which probably won't work. I was thinking that instead of using IdentityId, we could create a rule id and in the IdentityIdExtractor, we can decide which rule is applicable for a given id. Converting IdentityIdExtractor to Func<IHttpRequestProxy, class> or Func<IHttpRequestProxy, <string,string> instead of Func<IHttpRequestProxy, string> could solve this. Alternatively, is there an easier way to implement this that I am not seeing?

**Comment by scale-tone** [comment]
> Alternatively, is there an easier way to implement this that I am not seeing?

Hi @kayhantolga, if you want each of your 100K clients to be throttled *individually*, you just need to provide an **IdentityIdExtractor**.

As per [documentation](https://github.com/ThrottlingTroll/ThrottlingTroll/tree/main/ThrottlingTroll.AspNet#configuring-rules-and-limits): 
```
When IdentityIdExtractor is specified and IdentityId is not - different identityIds will automatically get their own rate counters, one counter per each unique identityId.
```

Let me know if I understood your usecase correctly.

**Comment by kayhantolga** [comment]
Hi, thanks for the reply. I understand the sample and have already tried it. It works quite well with a small number of clients. But in practice, injecting 100k rules will be quite challenging in terms of performance. So, I was thinking of grouping these clients. As an example, whoever has a gold subscription will have 100 requests per second, silver will have 10 requests per second, and bronze will have 1 request per second. This way, I only need to inject 3 rules. Additionally, I need to decide the user's rule in the `IdentityIdExtractor`.

**Comment by scale-tone** [comment]
> whoever has a gold subscription will have 100 requests per second, silver will have 10 requests per second, and bronze will have 1 request per second

Oh, that can be achieved [with a CostExtractor](https://github.com/ThrottlingTroll/ThrottlingTroll/blob/c1e946975fe8e24105a0ec7530eefb6279ca5f2a/samples/ThrottlingTrollSampleWeb/Program.cs#L300).

Set the limit to 100 coins, and then a bronze chap should be charged 100 coins per request, a silver guy should pay 10 coins and a gold fellow pays just 1.

Sounds good? :)

**Comment by kayhantolga** [comment]
Weirdly, I thought about that before but couldn't figure out how to implement it. But when I looked again, now it looks quite easy. Thanks a lot.
