### ISSUE TITLE
Default rule when using IdentityId

### ISSUE THREAD

**Issue by almightydegu** [ThrottlingTroll/ThrottlingTroll#20]
Hi, can we have a default rule on a URL when using IdentityId?

For example, I tried using this setup:

``` c#
Rules = new[]
{
    new ThrottlingTrollRule
    {
        UriPattern = "test$",
        IdentityId = "f411b023-dfb0-4756-9319-7bc24d11a682",
        LimitMethod = new FixedWindowRateLimitMethod
        {
            IntervalInSeconds = 1000,
            PermitLimit = 10
        }
    },
    new ThrottlingTrollRule
    {
        UriPattern = "test$",
        IdentityId = "758a3ff4-0655-4183-9406-20fbc8cb1bcc",
        LimitMethod = new FixedWindowRateLimitMethod
        {
            IntervalInSeconds = 1000,
            PermitLimit = 30
        }
    },
    new ThrottlingTrollRule
    {
        UriPattern = "test$",
        
        LimitMethod = new FixedWindowRateLimitMethod
        {
            IntervalInSeconds = 1000,
            PermitLimit = 1
        }
    }
}
```

I expected that anything that didn't have the identity of `f411b023-dfb0-4756-9319-7bc24d11a682` or `758a3ff4-0655-4183-9406-20fbc8cb1bcc` would use the third rule but using this setup everything goes through the first rule.

**Comment by scale-tone** [comment]
Hi @almightydegu , [an **IdentityId** is a no-op without an **IdentityIdExtractor**](https://github.com/ThrottlingTroll/ThrottlingTroll/blob/5d10358f003fa652d060b5af0ddc201f84b21394/ThrottlingTroll.Core/RequestFilter.cs#L125) (sorry if it is not clear from the documentation). That might be the reason of what you're observing.

Can you show your **IdentityIdExtractor**'s code?

**Comment by almightydegu** [comment]
Thank you for the reply @scale-tone.

Below is the full object I'm using:

``` c#
app.UseThrottlingTroll(options =>
{
    options.IdentityIdExtractor = request =>
    {
        return ((IIncomingHttpRequestProxy)request).Request.RouteValues["testId"]?.ToString();
    };

    options.Config = new ThrottlingTrollConfig
    {
        Rules = new[]
        {
            new ThrottlingTrollRule
            {
                UriPattern = "test$",
                IdentityId = "f411b023-dfb0-4756-9319-7bc24d11a682",
                LimitMethod = new FixedWindowRateLimitMethod
                {
                    IntervalInSeconds = 1000,
                    PermitLimit = 10
                }
            },
            new ThrottlingTrollRule
            {
                UriPattern = "test$",
                IdentityId = "758a3ff4-0655-4183-9406-20fbc8cb1bcc",
                LimitMethod = new FixedWindowRateLimitMethod
                {
                    IntervalInSeconds = 1000,
                    PermitLimit = 30
                }
            },
            new ThrottlingTrollRule
            {
                UriPattern = "test$",        
                LimitMethod = new FixedWindowRateLimitMethod
                {
                    IntervalInSeconds = 1000,
                    PermitLimit = 1
                }
            }
        }
    };
});
```
If I remove the third rule and just use the two rules that have the `IdentityId` set, then it works as expected, but I want to have a default option to the set up I want

**Comment by scale-tone** [comment]
Then I suggest you return some `my-default-identity-id` constant from your **IdentityIdExtractor**, when a request falls into this "default" category. And then have a separate **ThrottlingTrollRule** with **IdentityId**="my-default-identity-id".
That will not only work, but will also look explicit - leaves no doubt about how your system behaves.

Also remember, that **ThrottlingTrollRule.IdentityId** field is optional - when this value is omitted and **IdentityIdExtractor** is present, then all individual identities will get their separate counters automatically.

**Comment by almightydegu** [comment]
Doing that would mean all other requests would not be treated independently, which is what I was hoping for. I will need to create a rule for each of the IDs as a workaround. I mainly wanted this as a catch-all is a new ID is passed in without a rule and make the rules config cleaner to work with, but I can work around it
